import {
  Building2,
  Briefcase,
  Car,
  Landmark,
  Receipt,
  Calculator,
  PiggyBank,
  Wallet,
  Scale,
  Heart,
  Baby,
  Calendar,
  Clock,
  Binary,
  Function,
  Triangle,
  Square,
  Binary2,
  LineChart,
  Sigma,
  Network,
  Ruler,
  Zap,
  Users,
  Grid,
  Home,
  BadgeDollarSign,
  Building,
  CircleDollarSign,
  Coins,
  FileSpreadsheet,
  Weight,
  CalendarDays,
  Timer,
  Hash,
  Divide,
  LayoutGrid,
  Banknote,
} from "lucide-react";

export const calculatorIcons: Record<string, any> = {
  "/fangdai": Building2,
  "/shangyedaikuan": Briefcase,
  "/chedai": Car,
  "/gongjijin": Landmark,
  "/gerensuodeshui": Receipt,
  "/shuihougongzi": Calculator,
  "/wuxianyijin": PiggyBank,
  "/cunkuan": Banknote,
  "/gouzhishui": Scale,
  "/bmi": Weight,
  "/taiErtizhong": Baby,
  "/yuchanqi": Calendar,
  "/pailvnqi": CalendarDays,
  "/yuejing": Calendar,
  "/anquanqi": Timer,
  "/riqi": Calendar,
  "/shijian": Clock,
  "/nianling": Users,
  "/kexuejisuanqi": Calculator,
  "/jiefangcheng": Function,
  "/sanjiaohanshu": Triangle,
  "/kaigenghao": Square,
  "/shiliujinzhi": Binary2,
  "/duishu": LineChart,
  "/fangcha": Sigma,
  "/jiecheng": Hash,
  "/hanglieshi": LayoutGrid,
  "/ziwangyanma": Network,
  "/danweihuansuan": Ruler,
  "/dianyuan": Zap,
  "/qinqichenghu": Users,
  "/shudou": Grid,
  "/maifang": Home,
};